### PR TITLE
Move markdown files to docs

### LINKED ISSUE #161: Move markdown files to docs
While cleaning up the root directory in #120, I was thinking the many markdown files there perhaps are better at home in the full documentation. They can be included there as chapters. Specifically:

1. badges.md
2. CODE_OF_CONDUCT.md
3. CONTRIBUTING.md
4. ROADMAP.md

### PR DESCRIPTION
**Pull request by loostrum**
The following files were moved to the docs:
1. CODE_OF_CONDUCT.md
2. CONTRIBUTING.md
3. ROADMAP.md
4. CONTEXT.md

Links in the README were updated accordingly, but I had to guess the URLs (this does cause the markdown link checker to fail). 

I've also updated the docs copyright notice from 2021 to 2022.

Closes #161

### CODE REVIEW

**Review by elboyran — COMMENTED** [review]
Nice work, but 3 links to the moved files seem broken/dead.

**Comment by loostrum** [comment]
Thanks! Those should appear once this PR is merged, as then the readthedocs page is regenerated.

**Comment by elboyran** [comment]
> Thanks! Those should appear once this PR is merged, as then the readthedocs page is regenerated.

OK, merging then?

**Comment by loostrum** [comment]
Sounds good :) 
I'll merge and keep an eye on the links

**Comment by loostrum** [comment]
The links are working

**Pull request merged**
