### PR TITLE
Add tutorial for converting pytorch-lightning model to onnx

### LINKED ISSUE #335: Add PyTorch ligthing functionality for pytorch--> ONNX conversion tutorial
Update the [PyTorch to ONNX conversion tutoria](https://github.com/dianna-ai/dianna/blob/main/tutorials/conversion_onnx/pytorch2onnx.ipynb)l with PyTorch Lightning 2 ONNX export. See [Deploy models into production](https://pytorch-lightning.readthedocs.io/en/latest/deploy/production_advanced.html).

Or add a new short tutorial for PyTorch Lightning? Consider this [blog post](https://www.sabrepc.com/blog/Deep-Learning-and-AI/why-use-pytorch-lightning) for motivation ;-).

### PR DESCRIPTION
**Pull request by geek-yang**
Add tutorial of how to convert a pre-trained pytorch-lightning model to onnx.

This tutorial is added to the tutorial notebook of `pytorch2onnx.ipynb`.

To review this PR, run the notebook `pytorch2onnx.ipynb`.

Note: When working with `pytorch-lightning`, I found that there could be some import errors related to `pytorch-lightning`. To avoid these, please install the latest version of `pytorch-lightning`. I test it using `pytorch-lightning=1.7.7` and it works well.

This PR closes #335.

### CODE REVIEW

**Comment by geek-yang** [comment]
Note that the complaint from linter is not relevant with this PR. More details in issue #415.

**Comment by elboyran** [comment]
<p>Looks nice! I would only add PyTorch-lighting also in the title of the Notebook and also update the <a href="https://github.com/dianna-ai/dianna#onnx-models" target="_blank">README section about conversion</a>. just with 1 line summarizing the method like it's done for pytorch or just add pytorch-lighting also to the pytorch line.</p>

**Review by elboyran — CHANGES_REQUESTED** [review]
See my comment from the Notebook review.

**Comment by geek-yang** [comment]
> Looks nice! I would only add PyTorch-lighting also in the title of the Notebook and also update the [README section about conversion](https://github.com/dianna-ai/dianna#onnx-models). just with 1 line summarizing the method like it's done for pytorch or just add pytorch-lighting also to the pytorch line.

Thanks for your review @elboyran. I update the title inside the notebook to include pytorch-lightning and add a brief summary to the same line as pytorch in readme.

**Pull request merged**
