### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by elboyran**
Solves #679

### CODE REVIEW

**Review by geek-yang — APPROVED** [review]
Thanks for updating it! Looks great!

**Comment by cpranav93** [comment]
One suggestion:

- To be consistent with other entries in the table, it might good to add a line between the two models as done for time-series.

Otherwise looks great and the links work.

**Comment by elboyran** [comment]
> One suggestion:
> 
>     * To be consistent with other entries in the table, it might good to add a line between the two models as done for time-series.
> 
> 
> Otherwise looks great and the links work.

Hi @cpranav93 , what do you mean exactly? I cannot see a missing line, so probably I'm looking at the wrong place.

**Comment by cpranav93** [comment]
image

Although looking at the code, it seems like the line should be there and it may be a rendering issue on my web browser, so please ignore it if that's the case

**Comment by elboyran** [comment]
> image
> 
> Although looking at the code, it seems like the line should be there and it may be a rendering issue on my web browser, so please ignore it if that's the case

Thanks, you are fast! I was looking at the wrong README- my both PRs were called "Update README" ;-)

**Comment by elboyran** [comment]
> image
> 
> Although looking at the code, it seems like the line should be there and it may be a rendering issue on my web browser, so please ignore it if that's the case

Hmmm, in my branch there is already a line: 
image
image

**Pull request merged**
