### PR TITLE
Move docs logo to sidebar

### PR DESCRIPTION
**Pull request by loostrum**
Old situation:

image

New situation:

image

Unfortunately the logo is a png with white background, so it doesn't look as nice in the sidebar. @elboyran do you have a vector version of the logo? Or one with transparent background?

### CODE REVIEW

**Comment by elboyran** [comment]
Unfortunately, I do not have one with a transparent background (I've created it long ago just using Word fonts and symbols...).  I've tried online BG removal tools, but the result does not look so good. Would we know the exact color of the sidebar?

**Review by elboyran — APPROVED** [review]
Nice, that's the proper solution, indeed.

**Comment by loostrum** [comment]
Using the sidebar background color would be a good solution! I found the color in the Sphinx RTD theme CSS, it's hex [2980B9](https://www.color-hex.com/color/2980b9)

**Comment by loostrum** [comment]
Blue background version:

image

**Pull request merged**
