### PR TITLE
Create overviews of inputs outputs

### LINKED ISSUE #663: Create an overview (table?) of all input types and output types (including dimension names)
For both our XAI methods and the visualizations.
For using with dianna.explain but also RISE.explainer().explain
Also note if we are using Typing at these points.

Discuss the outcome with the team.

### PR DESCRIPTION
**Pull request by SarahAlidoost**
closes #663 
relates #691
preview [here](https://github.com/dianna-ai/dianna/blob/add_overview/docs/IO_overview.md).

### CODE REVIEW

**Comment by SarahAlidoost** [comment]
@elboyran I prepared tables listing input/output of methods/functions. I found most of them in either API documentation or the source code. Others like Dims/shape or some value ranges cannot be found in the doc. Please have a look at this PR and let me know if it can be further improved.

**Comment by elboyran** [comment]
again some notebooks are failing... @cpranav93 what was the trick?

**Comment by elboyran** [comment]
Very nice job, Sarah! 
The most tedious part is left and that is the dimensions and shapes as for that one needs to look inside the code. Any ideas how to make it quickly, maybe partially is enough?

**Review by elboyran — COMMENTED** [review]
Very nice job, Sarah! 
The most tedious part is left and that is the dimensions and shapes as for that one needs to look inside the code. Any ideas how to make it quickly, maybe partially is enough?

**Comment by SarahAlidoost** [comment]
> Very nice job, Sarah! The most tedious part is left and that is the dimensions and shapes as for that one needs to look inside the code. Any ideas how to make it quickly, maybe partially is enough?

Thank Elena for reviewing and for your comments. As we discussed, the difference in dimensions and shapes of **outputs** can be already seen in the `Type` columns in the output tables. I think we can merge this PR and as I fix issue #640, I will also update this document.

**Review by elboyran — APPROVED** [review]
Good job. Please, merge.

**Pull request merged**
