### PR TITLE
Fix remaining issues with dashboard and revise layout

### LINKED ISSUE #412: Duplications in dashboard/layout.py -> make generic function
There are quite some duplications of the code as these buttons are very similar to each other. It is better to look for some ways to only create one item and reuse them (e.g. usually in plain javascript, these things can be put together as a component for reuse). We'd better either find a simple solution for it in this PR,  just improve the readability of our code.

There are quite some duplications of the code as these buttons are very similar to each other. It is better to look for some ways to only create one item and reuse them (e.g. usually in plain javascript, these things can be put together as a component for reuse). We'd better either find a simple solution for it in this PR, or create an issue and fix this in next PR, just improve the readability of our code.

_Originally posted by @geek-yang in https://github.com/dianna-ai/dianna/pull/387#discussion_r1016875665_

### LINKED ISSUE #427: Dashboard: layout
Layout updates based on brainstorm with Jesus:
- Add headers for upload sections
- Make general DIANNA header less prominent
- Move XAI selection to method specific settings
- Move number of results to show to image prediction section
- For text tab: make text input multiline and section larger
- Optional: make Image/text tab selection prettier/more prominent

MicrosoftTeams-image

### LINKED ISSUE #454: create dashboard mockup
with ui improvements
also see #427

### LINKED ISSUE #522: Dashboard Move "show top N " button
Move "show top N " button to location under upload label file. See visual in #454 

Related to #521 
Related to #456 
Related to #479

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR fixes some of the issues defined in #549 

Resolves #454 - Most of the features of the mockup are present
Resolves #522 - I think the button is in a good place now
Resolves #412 - Dashboard has been refactored to share code between the tabs
Resolves #427 - No longer seems relevant

### CODE REVIEW

**Comment by stefsmeets** [comment]
This is what it looks like with all the suggestions applied:

### Images

Screenshot 2023-04-13 152444

### Text

Screenshot 2023-04-13 152647

**Comment by stefsmeets** [comment]
Hi @laurasootes Could you have a look at this one and let me know if you agree with the changes I made? 

The PR turned out a bit bigger than I intended, but I managed to implement all your suggestions in this one. I also did quite a bit of refactoring to reduce some duplication between the different pages.

Let me know what you think and if you still find any remaining issues.

**Review by laurasootes — APPROVED** [review]
Looks good!

Just a few things:
- Can you update the readme with the new dashboard file name?
- In the text tab: is there any way that you could make the label and text align when there is only one line of text?
image
- SonarCloud seems unhappy

Some suggestions to relax my OCD:
- can you switch the text and image at the home page so that they are in the same order as in the menu?
- Timeseries -> Time series
- home -> Home

**Comment by stefsmeets** [comment]
Thanks for the review @laurasootes , I addressed all your concerns. The sonarcloud warning is because of low coverage for the cli entry point for the dashboard, which is difficult to write a good test for.

I hope this adequately satisfies your OCD requirements: 

Screenshot 2023-04-13 110617

**Pull request merged**
