### PR TITLE
490 implement lime for timeseries

### PR DESCRIPTION
**Pull request by geek-yang**
In this PR, we implement LIME for timeseries based on `Lime-for-time` and `LimeSegmentation`, which are described in this paper https://doi.org/10.1016/j.jocs.2021.101539.

To make use of the maskers generator, this PR already includes the working progress in PR #494 (which is related to issue #477).

This PR closes issue #490.

### CODE REVIEW

**Comment by geek-yang** [comment]
Note that since the general explainer function for timeseries have already been implemented in PR #506 (https://github.com/dianna-ai/dianna/blob/d4b63b439a802d89f0355457e523c211e5830794/dianna/__init__.py#L35-L55), please don't re-implement that in this PR.

**Comment by cpranav93** [comment]
@geek-yang, Lime for time-series is working now in Dianna! Can you have a look? We can have a discussion about the format of the class maybe after you do.

**Comment by geek-yang** [comment]
> @geek-yang, Lime for time-series is working now in Dianna! Can you have a look? We can have a discussion about the format of the class maybe after you do.

Hi @cpranav93, good job! I tested it and it works very well with the coffee dataset. Follow our discussion, I made some changes and now it supports the api interface of dianna, which also works with onnx when you wrap it up as a model runner.

But when I try to test it with weather dataset, it doesn't work. I tried to make some changes to it but still didn't get any sensible result (you can find my test in the notebook `lime_timeseries_weather.ipynb`) . Since this PR is already super large, I suggest we wrap it up like this and continue our work in another PR.

**Comment by geek-yang** [comment]
Finally this big PR (about 1800 lines of code added) is ready for review. Note that this is the first step towards our own implementation of LIME for timeseries data and more need to be achieved to make it better. But now it already functions in a way that we can further polish it to improve the results from the explainer (and most importantly, it is integrated with our dianna api and you can run all notebooks without an error 😜).

In the code you will find many `TODO` things, which are listed below with a dedicated issue made for each of them:
- Adapt masking module for LIME timeseries #556 
- Fix first instance issue in LIME timeseries implementation #557
- Explore and verify distance method #558
- Merge duplication code of `_make_predictions` #559

Also, some results from the notebooks are not good enough, and they are expected to be improved when we fix issues related to the algorithm of LIME (due to the use of `lime_base` module) and implement smart segmentation strategy and masking for multiple channels. A new issue link to this is created as well for the improvement of the tutorial notebooks:
- Improve results in tutorial notebooks for LIME timeseries #560

Please for now just ignore these TODOs when you review this PR.

**Comment by cpranav93** [comment]
Great work @geek-yang! It really looks great now. The new issues you created will also be very helpful in improving our implementation of lime as well! Go ahead and merge.

**Review by cpranav93 — APPROVED** [review]

**Pull request merged**
