### PR TITLE
Add tabular example to getting start in readme

### LINKED ISSUE #686: Add tabular example in the Getting started section of the README.
Now we have text, image and time series example, but not tabular one (also the classification/regression version?).

### PR DESCRIPTION
**Pull request by geek-yang**
Add tabular example to getting start section in readme.

This PR closes #686 .

### CODE REVIEW

**Comment by elboyran** [comment]
There seems to be a dead link found by the markdown checker.

**Review by elboyran — APPROVED** [review]
Looks good to me, thanks!
The only remark I have is for "Run using the XAI methods of your choice.", We don't have RISE supported (yet). right? Maybe we still leave it like you wrote to be future proof.

**Comment by geek-yang** [comment]
> Looks good to me, thanks! The only remark I have is for "Run using the XAI methods of your choice.", We don't have RISE supported (yet). right? Maybe we still leave it like you wrote to be future proof.

Thanks for the review. We have both RISE and SHAP (soon to be merged) for now and plan to support RISE in the future. So I think  we can leave it like this.

**Comment by geek-yang** [comment]
> There seems to be a dead link found by the markdown checker.

It is due to a broken link for the joss badge. Not relevant with this PR, but it is fixed here.

**Pull request merged**
