### PR TITLE
Split RISE into separate classes for text and images (#91)

### PR DESCRIPTION
**Pull request by loostrum**

### CODE REVIEW

**Comment by loostrum** [comment]
It seems to be working fine for RISE. Should we split the other methods as well in this PR? Now there's some boilerplate needed in __init__.py because not all methods are split.

**Comment by loostrum** [comment]
Applied the split to LIME and KernelSHAP as well.

**Review by gcroci2 — APPROVED** [review]
Great! Seems very handy to have two separated class per data modality. Now adding functionalities to each method for each data modality will be much less complex.

**Comment by egpbos** [comment]
Excellent!

**Pull request merged**
