### PR TITLE
Remove explicit dtype conversion in SimpleModelRunner

### PR DESCRIPTION
**Pull request by loostrum**
Now that we keep track of the dtype of the data given by the user, we no longer 
need to do any conversion explicitly. 

This PR removes the explicit conversion to float32 in SimpleModelRunner, and adds explicit conversion
of the input data used in tests.

### CODE REVIEW

**Comment by loostrum** [comment]
Somewhat related to #59

**Comment by egpbos** [comment]
Also followup of #77, right?

**Review by egpbos — APPROVED** [review]
It's a bit difficult to envision all the reprecussions all this type mangling may have for users, but that is something that we have no tests for at this point, since we have no actual usecases of when it is a problem (if it ever will be a problem at all).

So, I think for now this is fine to merge :)

**Comment by egpbos** [comment]
There's a merge conflict now.

**Pull request merged**
