### PR TITLE
Add button to show/hide parameters

### LINKED ISSUE #414: Dashboard: create collapse menu for parameters
Maybe a nice to have:

create a dropdown menu in the dashboard for the model parameters:
https://dash-bootstrap-components.opensource.faculty.ai/docs/components/collapse/

(had a quick look at it, but noticed a potential issue with required stylesheet to have it actually collapse
`dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP]))`

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR adds a collapsible parameters section.

One issue is that this requires an external stylesheet that changes our layout slightly.

Follows up on #502 

Closes #414

### CODE REVIEW

**Comment by stefsmeets** [comment]
Hi @laurasootes , could you have a look and let me know if this is what you had in mind?

**Comment by laurasootes** [comment]
The collapsable parameter menu looks good! This exactly what we had in mind in terms of functionality.

However, this PR seems to have broken 3 things:
- the submit button reaches all the way to the side, there used to be some space here
- The select XXX is no longer light blue
- The update explanation buttons does not work in the text tab (does work in the image tab)

image

**Comment by stefsmeets** [comment]
Yeah, this is a side-effect of adding another style sheet. It clashes with all the inline styling done in the dashboard.

**Comment by laurasootes** [comment]
hmm, annoying. I presume it is fixable? 👼

**Comment by laurasootes** [comment]
For the image tab the run fails and gives an "tuple index out of range" when trying run it using RISE (not for the other methods, also not in text tab)

**Comment by stefsmeets** [comment]
> For the image tab the run fails and gives an "tuple index out of range" when trying run it using RISE (not for the other methods, also not in text tab)

Can you tell me your inputs? Because I don't see this happening on my side.
Can you also test if you see it in the main branch?

**Comment by laurasootes** [comment]
Turns out it was me, so no problems

**Review by laurasootes — APPROVED** [review]

**Pull request merged**
