### PR TITLE
Refactor dashboard

### PR DESCRIPTION
**Pull request by stefsmeets**
Trying to make sense of the dashboard for #414, I refactored the different elements to make it a bit easier to work with.

### CODE REVIEW

**Comment by stefsmeets** [comment]
Would this be useful for the project? Could you have a look @laurasootes ?

**Comment by laurasootes** [comment]
fixes https://github.com/dianna-ai/dianna/pull/497#issuecomment-1457888702

**Review by laurasootes — APPROVED** [review]
Thanks! Pulling apart these different parts already helps a lot. The images.py and text.py remain large and hard to read files, but I am not sure if/how we can make that better. I don't know if we should also try to pull apart some parts of the callbacks file

**Comment by laurasootes** [comment]
Only thing: you made the linter unhappy :)

**Comment by stefsmeets** [comment]
Thanks, the linter also makes *me* unhappy 😅
I will fix the issues and then merge 🚀

**Comment by laurasootes** [comment]
@stefsmeets I do not want to make you unhappy again, but the linter still is 😥

**Comment by stefsmeets** [comment]
This linting is madness. How do you guys work without auto-formatters that fix these automatically 😬

I can address this with #492 #493

**Comment by laurasootes** [comment]
Sounds like a plan. The lining is currently broken ~90% of the time

**Pull request merged**
