### PR TITLE
279 embeddings

### PR DESCRIPTION
**Pull request by cwmeijer**
Not yet ready for merging

### CODE REVIEW

**Comment by egpbos** [comment]
We should rename the DistanceExplainer to DistanceExplainerImage or something similar, like in #325.

**Comment by elboyran** [comment]
@cwmeijer , @egpbos do you plan to merge it? The SSP proposal promised that ;-)

**Comment by elboyran** [comment]
Also, the resulting software (if the distance explainer is in a separate package) is not specified on the RSD! Or rather the [software page](https://research-software-directory.org/software/explainable-embeddings) points only towards dianna (where the feature is missing).

**Comment by elboyran** [comment]
@cwmeijer , @egpbos shall we close this PR then?

**Comment by cwmeijer** [comment]
Work was continued in https://github.com/dianna-ai/distance_explainer.

**Pull request closed without merging**
