### PR TITLE
LIME on text tutorial

### PR DESCRIPTION
**Pull request by loostrum**
- Adds the movie reviews dataset
- Adds a LIME on text tutorial
- Fixes bug in highlight_text (it wouldn't show the html properly)

### CODE REVIEW

**Comment by loostrum** [comment]
@reviewer: the notebooks action is failing, but not on the notebook added in this PR so I'm ignoring it :)

**Comment by elboyran** [comment]
<p>@loostrum, nice notebook. Would you consider adding link to the method on Zenodo (once we put all of them there)? Probably I should make an issue for that...</p><p> </p>

**Comment by loostrum** [comment]
Thanks! I'd indeed change it once we have the models on zenodo (and we could then implement a download helper in dianan to automatically download them)
There's an issue already that somewhat covers it, I think: #108

**Comment by egpbos** [comment]
We need to retrigger CI, could you do an amend commit (`git commit --amend`) or rebase on main (`git rebase main` inside the PR branch, I tried it, it rebases automatically without conflicts) and force push to trigger it?

**Comment by egpbos** [comment]
Seems like this is ready, right?

**Comment by loostrum** [comment]
Yep, didn't merge yet because I wasn't sure if Elena reviewed all changes.

**Pull request merged**
