### PR TITLE
813 clean model folder

### LINKED ISSUE #813: Clean model folder
Preferably remove the folder completely
See #171

### PR DESCRIPTION
**Pull request by elboyran**
Removed from the repo the models and data that can be downloaded from Zenodo.

### CODE REVIEW

**Comment by elboyran** [comment]
@laurasootes any idea why the dashboard test is failing? 

I think it's not related to the removed models/data by this PR, but am not sure.

**Comment by elboyran** [comment]
To DO: fix the remaining issues in the RISE tabular penguin.

**Comment by loostrum** [comment]
I compared the files still present in the model folder with the downloader script and all seems to match - nice cleanup work!

**Comment by elboyran** [comment]
[like]  Elena Ranguelova reacted to your message:
________________________________

**Review by cwmeijer — APPROVED** [review]

**Pull request merged**
