### PR TITLE
create skeleton for joss paper

### PR DESCRIPTION
**Pull request by gcroci2**

### CODE REVIEW

**Review by elboyran — COMMENTED** [review]
Good work!

The link to the example figure fails. Maybe add a figure, e.g. the information one or the schematic one or even the logo, so it does pass?

**Comment by cwmeijer** [comment]
Looks great!
I moved the files to their own folder as not to infuriate the protector of the root folder @egpbos :-)
I also made the figure link to our Dianna logo in order to make it pass the tests.
I approve it as it is of course (as I made the latest changes), if anyone (@gcroci2 perhaps?) agrees that this solves #182 then please merge this.

**Comment by egpbos** [comment]
Before merging, be sure to check here whether it compiles as it should: https://whedon.theoj.org/

You can fill in `gcroci2-182_skeleton_joss` for the branch.

It compiles into something for me, but I didn't check whether it makes sense.

**Comment by egpbos** [comment]
Actually, I think it's fine. I just tried on `main` as well, and that fails, because it obviously can't find `paper.md` there. So, lgtm!

**Pull request merged**
